# Generated by Django 4.2.1 on 2023-05-05 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="book",
            name="source",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="file",
            field=models.FileField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="video",
            name="source",
            field=models.URLField(),
        ),
    ]
