# Generated by Django 4.2.1 on 2023-05-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_event_date_alter_book_source_alter_file_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(default=11, upload_to="images/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="files/"),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="file",
            field=models.FileField(upload_to="files/"),
        ),
    ]
