# Generated by Django 4.2.1 on 2023-07-03 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_content_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.RemoveField(
            model_name="file",
            name="date",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="date",
        ),
        migrations.RemoveField(
            model_name="video",
            name="date",
        ),
        migrations.AddField(
            model_name="content",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
