# Generated by Django 4.2.1 on 2023-05-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_user_avatar_user_image_alter_file_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interest",
            name="interested_in",
            field=models.ManyToManyField(related_name="interests", to="main.user"),
        ),
    ]
