# Generated by Django 4.2.1 on 2023-05-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_book_date_file_date_podcast_date_video_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="clickbait",
        ),
        migrations.AddField(
            model_name="content",
            name="image",
            field=models.ImageField(default=12, upload_to="images/"),
            preserve_default=False,
        ),
    ]
