# Generated by Django 4.2.1 on 2023-05-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_content_clickbait_content_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="image",
            field=models.ImageField(upload_to=".images/"),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=".files/"),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="file",
            field=models.FileField(upload_to=".files/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(upload_to=".images/"),
        ),
    ]
