# Generated by Django 4.2.1 on 2023-05-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_content_image_alter_file_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="tag",
            field=models.TextField(max_length=20, null=True),
        ),
    ]
