# Generated by Django 4.2.1 on 2023-06-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_content_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=".images/"),
        ),
    ]
