# Generated by Django 4.2.1 on 2023-06-28 19:17

import django.core.validators
from django.db import migrations, models
import main.custom_models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_content_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="image",
            field=main.custom_models.FileOrURLImageField(
                blank=True, null=True, upload_to=".images/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(5)]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=main.custom_models.FileOrURLImageField(
                blank=True, null=True, upload_to=".images/"
            ),
        ),
    ]
