# Generated by Django 4.2.1 on 2023-06-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_content_image_alter_user_age_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=".images/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=".images/"),
        ),
    ]
