# Generated by Django 4.2.1 on 2023-06-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_content_image_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="source",
            field=models.FileField(upload_to="files/books/"),
        ),
        migrations.AlterField(
            model_name="content",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=".images/cover_pages/"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=".files/files/"),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="file",
            field=models.FileField(upload_to=".files/podcasts/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=".images/avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="source",
            field=models.FileField(upload_to="files/videos/"),
        ),
    ]
